export const profileTypes = {
  LOADING: "PROFILE_LOADING",
  GET_USER: "GET_PROFILE_USER",
  FOLLOW: "FOLLOW",
  UN_FOLLOW: "UN_FOLLOW",
  GET_ID: "GET_PROFILE_ID",
  GET_POSTS: "GET_PROFILE_POSTS"
};
